name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    uses: kud/webext/.github/workflows/release-extension.yml@main
    with:
      ignore-files: publish.sh
    secrets: inherit
